
#TODO Make addFiles function

#' @title makeSetup
#' @description Project setup by screening a given folder for MS files or
#' by creating a new folder where the MS files can be added using \code{addFiles}.
#' Setting \code{createRproject} to \code{TRUE} will create and open an R project in the selected or given folder.
#' When \code{convertFiles} is \code{TRUE} the function uses \code{\link{mzMLconverter}} to automatically convert specified raw MS files to mzML.
#' 
#'
#' @param projPath The directory for the project. The default is the \code{utils::choose.dir()} to select or create a folder.
#' Note that the function will look into subfolders for mzML files or specified raw files when \code{convertFiles} is set to \code{TRUE}.
#' @param date The project date. The default is the system date generated by \code{\link[base]{Sys.time}}.
#' @param groups A vector with the identifier/name of each sample replicate group. If \code{NULL},
#' a grouping tentative will be made using the name of the MS files found in the given \code{projPath}.
#' @param blanks The name of the sample replicate group to be used for blank subtraction.
#' Different blank groups can be assigned to replicate sample groups by edditing the \code{sampleInfo} in the output \code{setup} list.
#' @param polarity A vector specifying the polarity mode used in each MS file.
#' Possible values are \code{positive} or \code{negative} for positive and negative mode, respectively.
#' @param convertFiles Logical, set to \code{TRUE} for non mzML MS files being converted to centroided mzML.
#' The default is \code{FALSE} for no conversion even if files are present.
#' @param convertFrom The name of the file format or vendor format to be found and converted.
#' Possible entries are: \emph{thermo}, \emph{bruker}, \emph{agilent}, \emph{ab} (from AB Sciex) and \emph{waters}.
#' @param convertToCentroid Logical, set to \code{TRUE} to convert profile data to centroided. The default and recommended is \code{TRUE}.
#' @param save Logical, set to \code{TRUE} to save the object setup in the \strong{rData} folder.
#' If \strong{rData} folder does not exist in given \code{projPath}, the folder will be created.
#' @param makeNewProject Logical, set to TRUE to create an R project in the given \code{projPath} and open a new R session.
#'
#' @return The output is a simple list, containing: (1) \code{projPath}, the chosen project path; (2) the \code{date}, the given project date; and 
#' (3) the \code{sampleInfo}, a \code{\link[base]{data.frame}} with the folowwing columns:
#' (1) \code{filePath}, the path of each mzML file, including any converted MS files;
#' (2) \code{sample}, the retrieved file name to be used as sample identifier;
#' (3) \code{group}, the name of each replicate sample group
#' (e.g. samples with the same name but with different numbering, such as in the case of replicate samples);
#' (4) \code{blank}, the specified blank group names or the blank group detected by file name (\emph{i.e.} blank, Blank and/or B as file name);
#' and (5) \code{polarity}, the polarity mode used for each sample, possible entries are \code{positive} and \code{negative};
#' 
#' 
#' @details The data.frame \code{sampleInfo} in the output list can always be eddited for correction of
#' sample replicate group names, blank replicate groups and assigned polarity, which is set to \code{positive} by default when not given as argument.
#' 
#' @export
#'
#' @importFrom tools file_path_sans_ext
#' @importFrom dplyr mutate
#' @importFrom rstudioapi initializeProject openProject
#'
#' @examples
#' 
#' 
#' 
makeSetup <- function(projPath = utils::choose.dir(base::getwd(), "Select or create a project folder"),
                      date = base::Sys.Date(),
                      groups = NULL,
                      blanks = NULL,
                      polarity = "positive",
                      convertFiles = FALSE,
                      convertFrom = NULL,
                      convertToCentroid = TRUE,
                      save = TRUE,
                      makeNewProject = FALSE) {
    
    #Examples
    # projPath <-  system.file(package = "ntsIUTA", dir = "extdata")
    # setup <- makeSetup(projPath = projPath, save = FALSE)
    # setup
    
    
    setup <- base::list()
    setup$projPath  <- projPath
    setup$date <- date
    
    #Create holder for list of samples
    sampleInfo <- base::data.frame(filePath = base::as.character(), sample = base::as.character(),
                                       group = base::as.character(), blank = base::as.character())
    
    
    if (convertFiles)
    {
        if (!base::is.null(convertFrom))
            ntsIUTA::mzMLconverter(path = projPath, convertFrom = convertFrom, centroidData = centroidData)
        else { stop("Vendors should be specified for file recognition. Possible entries are: thermo, bruker, agilent,
                 ab (from AB Sciex) and waters.") }
    }
    
    
    #Screen for MS files in project folder and add info to sampleInfo
    msFiles <- base::list.files(path = projPath, pattern = ".mzML|.mzXML", recursive = TRUE, full.names = TRUE, no.. = TRUE)
    
    if (base::length(msFiles) == 0)
    {
        warning("No mzML or mzXML files were found in selected project path. Use addFiles() to add files to project.")
    
    #Adds files info to sample data frame
    } else {
        sampleInfo[1:base::length(msFiles),] <- NA
        sampleInfo$filePath <- msFiles #base::dirname(msFiles)
        sampleInfo$sample <- tools::file_path_sans_ext(base::basename(msFiles))
        sampleInfo$blank <- blanks
        
        if (base::length(groups) < 2 & base::is.null(groups))
        {
            sampleInfo$group <- tools::file_path_sans_ext(base::basename(msFiles))
            #tentative to group samples and add blank group
            sampleInfo <- dplyr::mutate(sampleInfo, group = base::ifelse(base::grepl("A-r|qc|QC", sampleInfo$sample), "QC", group))
            sampleInfo <- dplyr::mutate(sampleInfo, group = base::ifelse(base::grepl("Blank|blank|B-r", sampleInfo$sample), "Blank", group))
            
        } else sampleInfo$group <- groups
        
        if (base::length(blanks) < 2 & base::is.null(blanks)) sampleInfo$blank <- base::ifelse("Blank" %in% sampleInfo$group, "Blank", NA)
        
        sampleInfo$polarity <- polarity
        
        setup$sampleInfo <- sampleInfo
    }
    
    
    if (save) #TODO Add possibility to move the R project file 
    {
        rData <- base::paste0(projPath,"\\rData")
        
        if (base::dir.exists(rData))
        {
            base::saveRDS(setup, file = base::paste0(rData,"\\setup.rds"))
        } else {
            base::dir.create(rData)
            base::saveRDS(setup, file = base::paste0(rData,"\\setup.rds"))
        }
    }
    
    
    if (makeNewProject)
    {
        #TODO add template for main script file
        sp <- base::file.path(projPath,"mainScript.R")
        base::cat(
            
"#Copy template from template.R using x and/or use ?ntsIUTA for a tutorial.\n
#Run the following code to load the project setup:\n
library(ntsIUTA) #/n
setup <- readRDS('rData/setup.rds')",
            
            file = sp, sep = "")
        rstudioapi::initializeProject(projPath)
        rstudioapi::openProject(projPath, newSession = TRUE)
        base::print("Run  rstudioapi::navigateToFile('mainScript.R')  in the new project to open the mainScript.R file.")
    }
    
    return(setup)
    
}







#' @title mzMLconverter
#' @description Converts MS files from different formats to mzML format.
#' See \pkg{patRoon} \insertCite{Helmus2021}{ntsIUTA} for all the possible formats. 
#' Optionally and recommended, it centroids the data.
#'
#' @param path The \code{path} where the files to be converted can be found. The function will look into subfolders.
#' @param convertFrom The format/vendor of files to be found and converted.
#' Possible entries are: \emph{thermo}, \emph{bruker}, \emph{agilent}, \emph{ab} (from AB Sciex) and \emph{waters}.
#' @param centroidData Logical, set to \code{TRUE} to convert profile data into centroided. The default and recommended is TRUE.
#'
#' @return The converted files will be saved as mzML in the given path.
#' 
#' @references \insertRef{Helmus2021}{ntsIUTA}
#' 
#' @export
#' 
#' @importFrom patRoon convertMSFiles
#' 
#'
#' @examples
#' 
#' 
#' 
mzMLconverter <- function(path = setup$projPath, convertFrom = "agilent", centroidData = TRUE) {
    
    #TODO add checking of inputFormats and other formats based on patRoom
    #TODO add check for ProteoWizard dependency in patRoon
    
    #Examples
    # mzMLconverter(path = system.file(package = "ntsIUTA", dir = "extdata"), convertFrom = "test")
    
    fileType <- NULL
    
    if (convertFrom == "agilent") fileType <- '.\\.d$'
    
    if (!base::is.null(fileType)) {
        rawFiles <- base::list.files(path = path, pattern = fileType,
                                     recursive = TRUE, full.names = TRUE,
                                     no.. = FALSE, include.dirs = TRUE, ignore.case = TRUE)
    }
    
    if(base::length(rawFiles) > 1)
    {
        if (centroidData)
        {
            #converts raw profile data into centroided mzML, with reduced space.
            patRoon::convertMSFiles(files = rawFiles,
                                    outPath = path,
                                    dirs = FALSE,
                                    anaInfo = NULL,
                                    from = convertFrom,
                                    to = "mzML",
                                    overWrite = FALSE,
                                    algorithm = "pwiz",
                                    centroid = "vendor",
                                    filters = c("msLevel 1-2"),
                                    extraOpts = NULL,
                                    PWizBatchSize = 1)
        } else {
            patRoon::convertMSFiles(files = rawFiles,
                                        outPath = path,
                                        dirs = FALSE,
                                        anaInfo = NULL,
                                        from = convertFrom,
                                        to = "mzML",
                                        overWrite = FALSE,
                                        algorithm = "pwiz",
                                        centroid = NULL,
                                        filters = NULL,
                                        extraOpts = NULL,
                                        PWizBatchSize = 1)    
            }
        
    } else {
        base::print("No files found with the given format or vendor!
                    Check if the files are in the folder or see documentation for the possible formats.")
        }
}



