

#' @title ntsData
#' @description S4 class object to organize and store processed data
#' within the \pkg{ntsIUTA} package.
#'
#' @slot title A character string with the project title.
#' @slot info A list to store project details.
#' The first position is for description of the project.
#' @slot path A character string with the project path.
#' as defined with \code{\link{setupProject}}.
#' @slot date The project date.
#' @slot polarity A string character defining the polarity mode of
#' the MS files in the \linkS4class{ntsData} object.
#' Possible values are "positive" or "negative".
#' @slot samples A \code{data.frame} as obtained by \code{\link{setupProject}}.
#' @slot metadata A \code{data.frame} with the same number of rows
#' as the \code{samples} containing metadata to support data interpretation.  
#' @slot parameters A list containing process parameters for the workflow steps.
#' @slot QC Slot for assigning the QC sample replicate group and results.
#' Note that the assigned group is not included in the basic workflow
#' but only used for quality control using the function \code{\link{qualityControl}}.
#' @slot MSnExp An \linkS4class{OnDiskMSnExp} as generated by \code{\link{setupProject}}.
#' @slot patdata A \linkS4class{features} or \linkS4class{featureGroups}
#' object derived from the basic NTS workflow
#' (peak picking, alignment and grouping).
#' @slot peaks A list with a data.frame containing the peak information
#' for each sample in the slot \code{samples}.
#' same length as number of rows with peak information.
#' @slot features data.frame.
#'
#' @return An S4 class object named \linkS4class{ntsData}. 
#' 
#' @note Slot \code{MSnExp} is used to save the \linkS4class{OnDiskMSnExp}
#' object obtained by \pkg{MSnbase} during the \code{\link{setupProject}}.
#' Slot \code{patdata} will contain the object \linkS4class{features} or
#' \linkS4class{featureGroups} generated from the \pkg{patRoon} package.
#' Both objects can be used within native functions of \pkg{MSnbase} and
#' \pkg{patRoon}.
#' 
#' @export
#'
#' @examples
#' 
setClass("ntsData",
  slots = c(
    title = "character",
    info = "list",
    path = "character",
    date = "Date",
    polarity = "character",
    samples = "data.frame",
    metadata = "data.frame",
    parameters = "list",
    QC = "list",
    MSnExp = "OnDiskMSnExp",
    patdata = "workflowStep",
    peaks = "data.frame",
    features = "data.frame"
  ),
  prototype = list(
    title = "New Project",
    info = list(description = NA_character_,
                history = list()),
    path = NA_character_,
    date = Sys.Date(),
    polarity = "positive",
    samples = data.frame(file = character(),
                         sample = character(),
                         group = character(),
                         blank = character()),
    metadata = data.frame(sample = character()),
    parameters = list(peakPicking = list(),
                      peakAlignment = list(),
                      peakGrouping = list(),
                      fillMissing = list()),
    QC = list(samples = data.frame(file = character(),
                                   sample = character(),
                                   group = character(),
                                   blank = character()),
              data = list(),
              results = list()),
    MSnExp = new("OnDiskMSnExp"),
    patdata = new("featuresXCMS3"),
    peaks = data.frame(),
    features = data.frame()
  )
)




#' @describeIn ntsData Informative printing.
#' @export
#' @importFrom dplyr count
setMethod("show", "ntsData", function(object) {
  
  st <- object@samples[,c("sample", "group", "blank")]
  if (nrow(object@peaks) > 0) {
    st$peaks <- count(object@peaks, sample)$n
  }
  
  cat(is(object)[[1]], "\n",
      "  Project: ", object@title, "\n",
      "  Date:  ", as.character(object@date), "\n",
      "  Path:  ", object@path, "\n",
      "  Polarity:  ", object@polarity, "\n",
      "  Sample details:  ", "\n", "\n", sep = "")
  
  if (nrow(st) > 0) rownames(st) <- 1:nrow(st)
  
  print(st)
  
  cat("\n")
  
  cat("  QC samples:  ", 
      ifelse(nrow(object@QC$samples) < 1, "empty", paste(object@QC$samples$sample, collapse = ", ")),
      "\n", " QC results:  ",
      ifelse(length(object@QC$results) < 1, "empty", "to add list of result objects"),
      "\n", set = "")
  
  cat("\n")
  
  cat("  Parameters:  ", "\n",
      "    ", "Peak picking: ", ifelse(length(object@parameters$peakPicking) > 0,
                                       class(object@parameters$peakPicking),
                                       "empty"), "\n",
      "    ", "Alignment: ", ifelse(length(object@parameters$peakAlignment) > 0,
                                    ifelse(length(object@parameters$peakAlignment) == 1,
                                           class(object@parameters$peakAlignment),
                                           class(object@parameters$peakAlignment[[1]])),
                                    "empty"), "\n",
      "    ", "Grouping: ", ifelse(length(object@parameters$peakGrouping) > 0,
                                   class(object@parameters$peakGrouping),
                                   "empty"), "\n",
      "    ", "Filling: ", ifelse(length(object@parameters$fillMissing) > 0,
                                  class(object@parameters$fillMissing),
                                  "empty"), "\n",
      sep = ""
  )
  
  cat("\n")
  
  cat("  MSnExp spectra:  ", length(object@MSnExp), "\n",
      "  MS level(s):  ", ifelse(length(object@MSnExp) > 0,
                                 paste(sort(unique(msLevel(object@MSnExp))), collapse = ", "),
                                 "-"), "\n",
      "  patRoon-class:  ", ifelse(length(object@patdata) > 0,
                                   class(object@patdata), "empty"), "\n",
      sep = ""
  )
  
  if (nrow(object@features) > 0) {
    cat("\n")
    cat(" Number of features:  ", nrow(object@features), "\n", sep = "")
  }
  
})




#' @describeIn ntsData Getter for samples.
#' @export
setMethod("samples", "ntsData", function(object) object@samples$sample)




#' @describeIn ntsData Getter for sample replicate groups.
#' @export
setMethod("sampleGroups", "ntsData", function(object) object@samples$group)


#' @describeIn ntsData Setter for sample replicate groups.
#' @export
setMethod("sampleGroups<-", "ntsData", function(object, value) {
  object@samples$group <- value
  return(object)
})




#' @describeIn ntsData Getter for blank replicate groups.
#' @export
setMethod("blanks", "ntsData", function(object) object@samples$blank)


#' @describeIn ntsData Setter for blank replicate groups.
#' @export
setMethod("blanks<-", "ntsData", function(object, value) {
  if (FALSE %in% unique(value %in% object@samples$group)) {
    error("Blank replicate sample groups must be one or more sample groups.")
  }
  object@samples$blank <- value
  return(object)
})



#' @describeIn ntsData Getter for QC replicate sample groups.
#' @export
setMethod("QC", "ntsData", function(object) object@QC$samples$sample)


#' @describeIn ntsData Setter for QC replicate sample groups.
#' @export
setMethod("QC<-", "ntsData", function(object, value) {
  if (FALSE %in% unique(value %in% object@samples$group)) {
    cat("Sample replicate group/s not found in the sample groups.")
  } else {
    object@QC$samples <- object@samples[object@samples$group %in% value,]
    object@samples <- object@samples[!(object@samples$group %in% value),]
  }
  return(object)
})




#' @describeIn ntsData Subset on samples.
#' @param \dots Ignored.
#' @export
#' @importMethodsFrom MSnbase filterFile
setMethod("[", c("ntsData", "ANY", "missing", "missing"), function(x, i, ...) {
  
  if (!missing(i)) {
    
    if (!is.character(i)) {
      sn <- x@samples$sample[i]
      sidx <- which(x@samples$sample %in% sn)
    } else {
        sn <- i
        sidx <- which(x@samples$sample %in% sn)
    }
    
    x@samples <- x@samples[x@samples$sample %in% sn, , drop = FALSE]
    x@metadata <- x@metadata[x@metadata$sample %in% sn, , drop = FALSE]
    if (length(x@MSnExp) > 0) x@MSnExp <- filterFile(x@MSnExp, file = sidx)
    if (nrow(x@peaks) > 0) x@peaks <- x@peaks[x@peaks$sample %in% sn, , drop = FALSE]
    if (nrow(x@features) > 0) {
      x@patdata@groups <- x@patdata@groups[sidx]
      x@patdata@ftindex <- x@patdata@ftindex[sidx]
      x@patdata@analysisInfo <- x@patdata@analysisInfo[sidx, ]
      x@patdata@features@features <- x@patdata@features@features[sidx]
      x@patdata@features@analysisInfo <- x@patdata@features@analysisInfo[fGroups@features@analysisInfo$analysis %in% sn, ]
      x <- buildFeatureList2(x)
    } else {
      if (length(x@patdata) > 0) x@patdata <- x@patdata[sn]
    }
    
  }
  
  return(x)
  
})

# TODO add method Peaks to see peaks from peaks table

# TODO add method Features to extract features from features table

# TODO make filter function/method and create filtering parameters slot
