

#' @title ntsData
#' @description S4 class object to organize and store processed data
#' within the \pkg{ntsIUTA} package.
#'
#' @slot title A character string with the project title.
#' @slot info A list to store project details.
#' The first position is for description of the project.
#' @slot path A character string with the project path.
#' as defined with \code{\link{setupProject}}.
#' @slot date The project date.
#' @slot polarity A string character defining the polarity mode of
#' the MS files in the \linkS4class{ntsData} object.
#' Possible values are "positive" or "negative".
#' @slot samples A \code{data.frame} as obtained by \code{\link{setupProject}}.
#' @slot metadata A \code{data.frame} with the same number of rows
#' as the \code{samples} containing metadata to support data interpretation.
#' @slot algorithms A list of algorithms used for the basic workflow steps,
#' which are \emph{Peak Picking}, \emph{Make Features} and \emph{Annotation}. 
#' @slot parameters A list containing process parameters for the workflow steps.
#' @slot QC Slot for assigning the QC sample replicate group and results.
#' Note that the assigned group is not included in the basic workflow
#' but only used for quality control, using the function \code{\link{checkQC}},
#' and for optimization of workflow parameters. A screening list with target substances
#' must be provided for running quality control.
#' @slot MSnExp An \linkS4class{OnDiskMSnExp} as generated by \code{\link{setupProject}}.
#' @slot patdata A \linkS4class{features} or \linkS4class{featureGroups}
#' object derived from the basic NTS workflow
#' (peak picking, alignment and grouping).
#' @slot peaks A list with a data.frame containing the peak information
#' for each sample in the slot \code{samples}.
#' same length as number of rows with peak information.
#' @slot features data.frame.
#' @slot annotation Slot for storage of annotation of isotopes and adducts and
#' source fragments. Features with similar chromatographic behaviour
#' are grouped by components. Isotopologues are grouped by \code{isonumber} and
#' are created for each sample replicate group. Similarly, adducts are searched
#' for each sample replicate group and share the same molecular ion (\code{Mion}).
#' The functionality of the package \pkg{CAMERA} was adapted to work better for
#' environmental analyses, where sample replicate groups are, in principle,
#' very different from each other. When specified other functionalities
#' from the package \pkg{patRoon} can be used but the default
#' is the package \pkg{CAMERA} directly. The slot is composed of a list of length 2,
#' where the first entry is a data frame with summarized results for each feature
#' and the second is the raw data from the \pkg{CAMERA} package.
#'
#' @return An S4 class object named \linkS4class{ntsData}. 
#' 
#' @note Slot \code{MSnExp} is used to save the \linkS4class{OnDiskMSnExp}
#' object obtained by \pkg{MSnbase} during the \code{\link{setupProject}}.
#' Slot \code{patdata} will contain the object \linkS4class{features} or
#' \linkS4class{featureGroups} generated from the \pkg{patRoon} package.
#' Both objects can be used within native functions of \pkg{MSnbase} and
#' \pkg{patRoon}.
#' 
#' @export
#'
#' @examples
#' 
setClass("ntsData",
  slots = c(
    title = "character",
    info = "list",
    path = "character",
    date = "Date",
    polarity = "character",
    samples = "data.frame",
    metadata = "data.frame",
    algorithms = "list",
    parameters = "list",
    QC = "list",
    MSnExp = "OnDiskMSnExp",
    patdata = "workflowStep",
    peaks = "data.frame",
    features = "data.frame",
    annotation = "list"
  ),
  prototype = list(
    title = "New Project",
    info = list(description = NA_character_,
                history = list()),
    path = NA_character_,
    date = Sys.Date(),
    polarity = "positive",
    samples = data.frame(file = character(),
                         sample = character(),
                         group = character(),
                         blank = character()),
    metadata = data.frame(sample = character()),
    algorithms = list(peakPicking = NA_character_,
                      makeFeatures = NA_character_,
                      annotation = NA_character_),
    parameters = list(peakPicking = list(),
                      peakAlignment = list(),
                      peakGrouping = list(),
                      fillMissing = list(),
                      annotation = list()),
    QC = list(samples = data.frame(file = character(),
                                   sample = character(),
                                   group = character(),
                                   blank = character()),
              targets = data.frame(),
              data = list(),
              results = list()),
    MSnExp = new("OnDiskMSnExp"),
    patdata = new("featuresXCMS3"),
    peaks = data.frame(),
    features = data.frame(),
    annotation = list(df = data.frame(),
                      raw = list())
  )
)


### show -----

#' @describeIn ntsData Informative printing.
#' @export
#' @importFrom dplyr count
setMethod("show", "ntsData", function(object) {
  
  st <- object@samples[,c("sample", "group", "blank")]
  if (nrow(object@peaks) > 0) {
    st$peaks <- count(object@peaks, sample)$n
  }
  
  cat(is(object)[[1]], "\n",
      "  Project: ", object@title, "\n",
      "  Date:  ", as.character(object@date), "\n",
      "  Path:  ", object@path, "\n",
      "  Polarity:  ", object@polarity, "\n",
      "  Sample details:  ", "\n", "\n", sep = "")
  
  if (nrow(st) > 0) rownames(st) <- 1:nrow(st)
  
  print(st)
  
  cat("\n")
  
  cat("  QC samples:  ", 
      ifelse(nrow(object@QC$samples) < 1, "empty", paste(object@QC$samples$sample, collapse = ", ")),
      "\n", " QC results:  ",
      ifelse(length(object@QC$results) < 1, "empty", "to add list of result objects"),
      "\n", set = "")
  
  cat("\n")
  
  cat("  Algorithms:  ", "\n",
      "    ", "Peak Picking: ", ifelse(!is.na(object@algorithms$peakPicking),
                                       object@algorithms$peakPicking,
                                       "empty"), "\n",
      "    ", "Make Features: ", ifelse(!is.na(object@algorithms$makeFeatures),
                                        object@algorithms$makeFeatures,
                                        "empty"), "\n",
      "    ", "Annotation: ", ifelse(!is.na(object@algorithms$annotation) > 0,
                                     object@algorithms$annotation,
                                     "empty"), "\n",
      sep = ""
  )
  
  cat("\n")
  
  cat("  Parameters:  ", "\n",
      "    ", "Peak Picking: ", ifelse(length(object@parameters$peakPicking) > 0,
                                       class(object@parameters$peakPicking),
                                       "empty"), "\n",
      "    ", "Alignment: ", ifelse(length(object@parameters$peakAlignment) > 0,
                                    ifelse(length(object@parameters$peakAlignment) == 1,
                                           class(object@parameters$peakAlignment),
                                           class(object@parameters$peakAlignment[[1]])),
                                    "empty"), "\n",
      "    ", "Grouping: ", ifelse(length(object@parameters$peakGrouping) > 0,
                                   class(object@parameters$peakGrouping),
                                   "empty"), "\n",
      "    ", "Filling: ", ifelse(length(object@parameters$fillMissing) > 0,
                                  class(object@parameters$fillMissing),
                                  "empty"), "\n",
      "    ", "Annotation: ", ifelse(length(object@parameters$annotation) > 0,
                                  class(object@parameters$annotation),
                                  "empty"), "\n",
      sep = ""
  )
  
  cat("\n")
  
  cat("  MSnExp spectra:  ", length(object@MSnExp), "\n",
      "  MS level(s):  ", ifelse(length(object@MSnExp) > 0,
                                 paste(sort(unique(msLevel(object@MSnExp))), collapse = ", "),
                                 "-"), "\n",
      "  patRoon-class:  ", ifelse(length(object@patdata) > 0,
                                   class(object@patdata), "empty"), "\n",
      sep = ""
  )
  
  if (nrow(object@features) > 0) {
    cat("\n")
    cat(" Number of features:  ", nrow(object@features), "\n", sep = "")
  }
  
})


### samples -----

#' @describeIn ntsData Getter for samples.
#' @export
setMethod("pullSamples", "ntsData", function(object) object@samples$sample)


### samplegroups -----

#' @describeIn ntsData Getter for sample replicate groups.
#' @export
setMethod("pullSamplegroups", "ntsData", function(object) object@samples$group)

#' @describeIn ntsData Setter for sample replicate groups.
#' @export
setMethod("pushSamplegroups", "ntsData", function(object, value) {
  object@samples$group <- value
  return(object)
})

#' @describeIn ntsData Setter for sample replicate groups.
#' @export
setMethod("pushSamplegroups<-", "ntsData", function(object, value) {
  object@samples$group <- value
  return(object)
})


### blanks -----

#' @describeIn ntsData Getter for blank replicate groups.
#' @export
setMethod("pullBlanks", "ntsData", function(object) object@samples$blank)

#' @describeIn ntsData Setter for blank replicate groups.
#' @export
setMethod("pushBlanks", "ntsData", function(object, value) {
  if (FALSE %in% unique(value %in% object@samples$group)) {
    error("Blank replicate sample groups must be one or more sample groups.")
  }
  object@samples$blank <- value
  return(object)
})

#' @describeIn ntsData Setter for blank replicate groups.
#' @export
setMethod("pushBlanks<-", "ntsData", function(object, value) {
  if (FALSE %in% unique(value %in% object@samples$group)) {
    error("Blank replicate sample groups must be one or more sample groups.")
  }
  object@samples$blank <- value
  return(object)
})


### QC -----

#' @describeIn ntsData Getter for QC replicate sample groups.
#' @export
setMethod("pullQC", "ntsData", function(object) object@QC$samples$sample)


#' @describeIn ntsData Setter for QC replicate sample groups.
#' @export
setMethod("pushQC<-", "ntsData", function(object, value) {
  if (FALSE %in% unique(value %in% object@samples$group)) {
    cat("Sample replicate group/s not found in the sample groups.")
  } else {
    object@QC$samples <- object@samples[object@samples$group %in% value,]
    object@samples <- object@samples[!(object@samples$group %in% value),]
  }
  return(object)
})


### [ sub-setting -----

#' @describeIn ntsData Subset on samples.
#' @param \dots Ignored.
#' @export
#' @importMethodsFrom MSnbase filterFile fileNames
#' @importMethodsFrom xcms filterFile
setMethod("[", c("ntsData", "ANY", "missing", "missing"), function(x, i, ...) {
  
  if (!missing(i)) {
    
    if (!is.character(i)) {
      sn <- x@samples$sample[i]
      sidx <- which(x@samples$sample %in% sn)
    } else {
        sn <- i
        sidx <- which(x@samples$sample %in% sn)
    }
    
    x@samples <- x@samples[x@samples$sample %in% sn, , drop = FALSE]
    
    x@metadata <- x@metadata[x@metadata$sample %in% sn, , drop = FALSE]
    
    if (length(x@MSnExp) > 0) x@MSnExp <- filterFile(x@MSnExp, file = sidx)
    
    if (nrow(x@peaks) > 0) x@peaks <- x@peaks[x@peaks$sample %in% sn, , drop = FALSE]
    
    if (nrow(x@features) > 0) {
      x@patdata@groups <- x@patdata@groups[sidx]
      x@patdata@ftindex <- x@patdata@ftindex[sidx]
      x@patdata@analysisInfo <- x@patdata@analysisInfo[sidx, ]
      x@patdata@features@features <- x@patdata@features@features[sidx]
      x@patdata@features@analysisInfo <- x@patdata@features@analysisInfo[x@patdata@features@analysisInfo$analysis %in% sn, ]
      if (x@patdata@algorithm == "xcms3") {
        files <- basename(fileNames(x@patdata@xdata)[sidx])
        x@patdata@xdata <- filterFile(x@patdata@xdata, files)
        x@patdata@features@xdata <- filterFile(x@patdata@features@xdata, files)
      }
      x <- buildFeatureList2(x)
      
    } else {
      if (length(x@patdata) > 0) {
        x@patdata@features <- x@patdata@features[sidx]
        x@patdata@analysisInfo <- x@patdata@analysisInfo[x@patdata@analysisInfo$analysis %in% sn, ]
        if (x@patdata@algorithm == "xcms3") {
          files <- basename(fileNames(x@patdata@xdata)[sidx])
          x@patdata@xdata <- filterFile(x@patdata@xdata, files)
        }
      }
    }
  }
  
  return(x)
  
})


### peaks -----

#' @describeIn ntsData Getter for chromatographic peaks.
#' @export
setMethod("pullPeaks", "ntsData", function(obj,
                                           fileIndex = NULL, ID = NULL,
                                           mz = NULL, ppm = 20,
                                           rt = NULL, rtWindow = NULL,
                                           rtUnit = "sec") {
  
  if (nrow(obj@peaks) == 0) return(cat("ntsData object does not have peaks."))
  checkmate::checkSubset(rtUnit, c("sec", "min"))
  
  if (!is.null(fileIndex)) obj <- filterFileFaster(obj, fileIndex)
  
  rtr <- NULL
  
  if (!is.null(ID)) {
    pk <- obj@peaks[obj@peaks$ID %in% ID, ]
  } else {
    if (!is.null(mz)) {
      mzr <- mzrBuilder(mz = mz, ppm = ppm)
      rtr <- rtrBuilder(rt = rt, rtWindow = rtWindow, rtUnit = rtUnit)
      pk <- dplyr::filter(obj@peaks,
                          dplyr::between(mz, mzr[1], mzr[2]),
                          dplyr::between(rt, rtr[1], rtr[2]))
    } else {
      return(cat("One of ID or mz should be given."))
    }
  }
  
  if (nrow(pk) == 0) return(cat("No peaks found."))
  
  return(pk)
  
})


### features -----

#' @describeIn ntsData Getter for features (i.e., grouped peaks).
#' @export
setMethod("pullFeatures", "ntsData", function(obj,
                                              fileIndex = NULL, ID = NULL,
                                              mz = NULL, ppm = 20,
                                              rt = NULL, rtWindow = NULL,
                                              rtUnit = "sec") {
  
  if (nrow(obj@features) == 0) return(cat("ntsData object does not have features."))
  checkmate::checkSubset(rtUnit, c("sec", "min"))
  
  if (!is.null(fileIndex)) obj <- filterFileFaster(obj, fileIndex)
  
  rtr <- NULL
  
  if (!is.null(ID)) {
    ft <- obj@features[obj@features$ID %in% ID, ]
  } else {
    if (!is.null(mz)) {
      mzr <- mzrBuilder(mz = mz, ppm = ppm)
      rtr <- rtrBuilder(rt = rt, rtWindow = rtWindow, rtUnit = rtUnit)
      ft <- dplyr::filter(obj@features,
                          dplyr::between(mz, mzr[1], mzr[2]),
                          dplyr::between(rt, rtr[1], rtr[2]))
    } else {
      return(cat("One of ID or mz should be given."))
    }
  }
  
  if (nrow(ft) == 0) return(cat("No peaks found."))
  
  return(ft)
  
})


# TODO make filter function/method and create filtering parameters slot
